# Generated by Django 3.1.7 on 2021-03-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_auto_20210305_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='img',
            field=models.ImageField(upload_to='land'),
        ),
    ]
