# Generated by Django 3.2 on 2021-05-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Did', models.CharField(max_length=20)),
                ('temp', models.FloatField(default=0.0)),
                ('moisture', models.FloatField(default=0.0)),
                ('ph', models.FloatField(default=0.0)),
            ],
        ),
    ]
