# Generated by Django 3.2 on 2021-05-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_rename_land_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='landtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=5)),
                ('land_type', models.CharField(max_length=35)),
                ('land_area', models.FloatField(max_length=8)),
            ],
        ),
        migrations.RenameModel(
            old_name='profilepic',
            new_name='profilepic1',
        ),
    ]
