# Generated by Django 3.2 on 2021-05-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20210504_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtype',
            name='cropselected',
            field=models.CharField(default='rice', max_length=35),
        ),
        migrations.AlterField(
            model_name='landtype',
            name='land_type',
            field=models.CharField(default='clay soil', max_length=35),
        ),
    ]
